# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sappsapp', '0003_auto_20180121_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='disc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='fil',
            field=models.FileField(upload_to='documents/asignments'),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='topic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resources',
            name='disc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resources',
            name='topic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resources',
            name='video',
            field=models.FileField(upload_to='documents/video'),
        ),
        migrations.AlterField(
            model_name='univresults',
            name='res1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='univresults',
            name='sub1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
