# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 07:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sappsapp', '0005_auto_20180121_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqs',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mcqs',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignments',
            name='disc',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resources',
            name='disc',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
